name: Deploy to Firebase

on:
  push:
    branches:
      - master  # メインブランチにプッシュされた時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'  # プロジェクトで使用しているNode.jsのバージョンに合わせてください

      - name: Install dependencies
        run: npm ci

      - name: Build and Deploy
        run: |
          npm run build
          npx firebase-tools deploy --only hosting --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
