name: Deploy using Makefile

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Execute Makefile deploy
      run: make deploy
