name: Deploy to Firebase

on:
  push:
    branches:
      - master  # メインブランチにプッシュされた時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'  # Node.jsのバージョンを18.18.0に更新

      - name: Clean up package manager files
        run: |
          rm -f package-lock.json
          rm -f yarn.lock

      - name: Install dependencies
        run: npm install  # Yarnの代わりにnpm installを使用

      - name: Build
        run: npm run build  # npm run buildを使用

      - name: List files in the repository
        run: |
          echo "Root directory:"
          ls -la
          echo "Dist directory:"
          ls -la dist

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
