name: Deploy to Firebase

on:
  push:
    branches:
      - master  # メインブランチにプッシュされた時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'  # ローカル環境と同じバージョンを指定

      - name: Install dependencies
        run: yarn install --frozen-lockfile  # yarnを使用していることが確認できたので、npm ciからyarn installに変更

      - name: Build
        run: yarn build  # npm run buildからyarn buildに変更

      - name: List files in the repository
        run: |
          echo "Root directory:"
          ls -la
          echo "Dist directory:"
          ls -la dist

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
